# Generated by Django 4.1.1 on 2022-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='l_name',
        ),
        migrations.AddField(
            model_name='about',
            name='first_Name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='about',
            name='last_Name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='about',
            name='city',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='hobbies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='interests',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='power',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
