# Generated by Django 4.1.1 on 2022-10-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_about_f_name_remove_about_l_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
